services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        depends_on:
            - db
        env_file:
            - .env
        volumes:
            - ./logs:/app/logs

    db:
        image: mysql:8.0
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - mysql_data:/var/lib/mysql
            - ./dump.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - '3306:3306'

volumes:
    mysql_data:
