[versions]
kotlin = "1.5.30"

connector = "8.0.25"
dotenv = "6.2.2"
groovy = "3.0.8"
kord-extensions = "1.5.1-RC1"
logging = "2.0.11"
logback = "1.2.5"
serialization = "1.3.1"

[libraries]
connector = { module = "mysql:mysql-connector-java", version.ref = "connector" }
dotEnv = { module = "io.github.cdimascio:dotenv-kotlin", version.ref = "dotenv" }
groovy = { module = "org.codehaus.groovy:groovy", version.ref = "groovy" }
kord-extensions = { module = "com.kotlindiscord.kord.extensions:kord-extensions", version.ref = "kord-extensions" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logging = { module = "io.github.microutils:kotlin-logging", version.ref = "logging" }
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
