[versions]
kotlin = "1.6.10"

connector = "8.0.27"
datetime = "0.3.2"
dotenv = "6.2.2"
groovy = "3.0.9"
kord-base = "0.8.x-SNAPSHOT"
kord-extensions = "1.5.2-RC1"
logging = "2.1.21"
logback = "1.2.8"
serialization = "1.3.2"

[libraries]
connector = { module = "mysql:mysql-connector-java", version.ref = "connector" }
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
dotEnv = { module = "io.github.cdimascio:dotenv-kotlin", version.ref = "dotenv" }
groovy = { module = "org.codehaus.groovy:groovy", version.ref = "groovy" }
kord-base = { module = "dev.kord:kord-core", version.ref = "kord-base" }
kord-extensions = { module = "com.kotlindiscord.kord.extensions:kord-extensions", version.ref = "kord-extensions" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logging = { module = "io.github.microutils:kotlin-logging-jvm", version.ref = "logging" }
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
